version: '3.8'

services:
  login:
    image: gosikhena/login-app:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  registration:
    image: gosikhena/registration-app:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  resume:
    image: gosikhena/resume-app:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
