version: '3.8'
services:
  login:
    image: gosikhena/login:latest
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == manager]
    ports:
      - target: 80
        published: 81
        protocol: tcp
        mode: host

  registration:
    image: gosikhena/registration:latest
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == manager]
    ports:
      - target: 80
        published: 82
        protocol: tcp
        mode: host

  resume:
    image: gosikhena/resume:latest
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == manager]
    ports:
      - target: 80
        published: 83
        protocol: tcp
        mode: host
